### ISSUE TITLE
Runtime Error - ActorSystem not found

### ISSUE THREAD

**Issue by icarius06** [icarius06/First-Akka#1]
<p>Executing the command java -jar first-akka-1.0-SNAPSHOT.jar  to run jarred Main class causes the following error.Possibly can not see config.jar in classpath. Works in IDE </p>
<p>
<code>
Exception in thread "main" java.lang.NoClassDefFoundError: akka/actor/ActorSystem
	at co.m800.assgnt.akka.App.main(App.java:31)
Caused by: java.lang.ClassNotFoundException: akka.actor.ActorSystem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
</code> </p>

**Comment by icarius06** [comment]
Moot
